import { z } from 'zod';
import { UuidSchema, IsoDateSchema } from './common.schema';

/**
 * Standard Audit Log Entry Schema.
 * Defines the structure for immutable audit logs as per REQ-AUDIT-001.
 */
export const AuditLogEntrySchema = z.object({
  logId: UuidSchema.optional(), // Can be generated by DB
  timestamp: IsoDateSchema,
  actor: z.object({
    userId: UuidSchema,
    userRole: z.string(),
    sourceIpAddress: z.string().ip().optional().nullable(),
    userAgent: z.string().optional().nullable(),
  }),
  action: z.string().min(1, 'Action type is required'), // e.g. "BRAND_APPROVED"
  outcome: z.enum(['SUCCESS', 'FAILURE', 'PARTIAL']),
  target: z.object({
    entityType: z.string(),
    entityId: z.string(),
    context: z.record(z.any()).optional(), // Additional context like "OldValue -> NewValue"
  }),
  details: z.record(z.any()).optional(),
});

export type AuditLogEntry = z.infer<typeof AuditLogEntrySchema>;